#!/bin/bash

VERSION=1.5.1

wget http://dl.bintray.com/gitblit/releases/gitblit-${VERSION}.war
mkdir -p ROOTFS/usr/tomcat/webapps/gitblit
cd ROOTFS/usr/tomcat/webapps/gitblit
unzip -x ../../../../../gitblit-${VERSION}.war


